# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/repo-aws-ldk
  docker:
    - image: circleci/node:8.9.1

jobs:
  test:
    <<: *defaults  
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-files-{{ .Environment.CIRCLE_SHA1 }}
    # fallback to using the latest cache if no exact match is found
          - v1-files-{{ .Environment.CIRCLE_SHA1 }}

      - run: npm install
      - run:
          name: Run tests
          command: npm run test

      - save_cache:
          paths:
            - ./
          key: v1-files-{{ .Environment.CIRCLE_SHA1 }}

      - persist_to_workspace:
          root: ~/repo-aws-ldk
          paths: .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo-aws-ldk
          
      - restore_cache:
          keys:
          - v1-files-{{ .Environment.CIRCLE_SHA1 }}
          
      - run: 
          name: info
          command: |
            echo $PWD
            ls -a
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo-aws-ldk/.npmrc
      - run:
          name: Publish version
          command: npm version 0.3.${CIRCLE_BUILD_NUM}
      - run:
          name: Publish package
          command: npm publish
workflows:
  version: 2
  test-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master